name: ${project.name}
main: net.daboross.bukkitdev.bandata.BanDataplugin
version: ${project.version}
author: Dabo Ross
description: This plugin is an extension of PlayerData that records BanData
depend: [Vault, PlayerData]
commands:
   bd:
     description: This is the base command for Ban Data.
     usage: /<command> ?
     aliases: [bandata, bdata, bandata]
permissions:
  bandata.*:
    description: Gives access to all BanData commands
    children:
      bandata.help: true
      bandata.viewban: true
      bandata.listbans: true
      bandata.bantp: true
      bandata.ban: true
      bandata.admin: true
    default: false
  bandata.help:
    description: Allows you to use /bd ?
    default: true
  bandata.baninfo:
    description: allows you to view Ban Info.
    default: true
    children:
      bandata.help: true
  bandata.viewban:
    description: Allows you to view Ban Data.
    default: true
    children:
      bandata.help: true
      bandata.baninfo: true
  bandata.listbans:
    description: Allows you to List All Bans
    default: true
    children:
      bandata.help: true
  bandata.bantp:
    description: Allows you to teleport to ban locations
    default: true
    children:
      bandata.help: true
  bandata.ban:
    description: Allows you to Ban Users.
    default: false
    children:
      bandata.help: true
      bandata.baninfo: true
      bandata.listbans: true
      bandata.bantp: true
  bandata.admin:
    description: Ban Data admin.
    default: false
    children:
      bandata.help: true
      bandata.baninfo: true
      bandata.listbans: true
      bandata.bantp: true
  bandata.unban:
    description: Allows you to UnBan players
    default: false
    children:
      bandata.help: true
      bandata.baninfo: true
      bandata.listbans: true
      bandata.bantp: true